### ISSUE TITLE
For LeDoux Course : Update index folder 

### ISSUE THREAD

**Issue by amaze18** [amaze18/LeDoux#1]
For LeDoux Course : Update index folder with index of VidyaRang ledoux course and then test if answers in the streamlit app: https://4realms-existence.streamlit.app/ are same as in VidyaRang ledoux course

**Comment by SaiGane5** [comment]
Updated Index folder with VidyaRANG's Index folder and modified some code in Hybrid Retriever class, now the results are same as VidyaRANG
