### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by amaze18** [amaze18/LeDoux#5]
FileNotFoundError: [Errno 2] No such file or directory: 

'/mount/src/ledoux/F2B/docstore.json'

https://github.com/amaze18/LeDoux/blob/F2B/streamlit_app.py

resolve it @SaiGane5

**Comment by SaiGane5** [comment]
Uploaded the necessary json files from course_chat_large ec2
